name: Update POT file

on:
  push:
    branches:
    - dev
    paths:
    - '**.php'
    - '**.js'

jobs:
  update-pot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install xgettext
      run: sudo apt-get install -y gettext
    - name: Update POT
      run: npm run pot
    - name: Commit updated POT
      uses: stefanzweifel/git-auto-commit-action@v4.1.1
      with:
        commit_message: 'chore(localization): update resources/lang/pcc.pot'
